### ISSUE TITLE
Dissector unable to parse trace.

### ISSUE THREAD

**Issue by tiferrei** [QUIC-Tracker/dissector#1]
Hey!
 
I got this trace from a connection to a local MsQuic server. It should show the client sending a ClientHello, and the server replying with a Retry, however when I pass this to QUIC-Tracker I get an exception about the dissection:
```
127.0.0.1 - - [29/Jul/2020 15:22:09] "GET /traces/20200729/0 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tiferrei/Developer/web-app/quic_tracker/app.py", line 101, in dissector
    trace = parse_trace(traces[trace_idx])
  File "/Users/tiferrei/Developer/web-app/quic_tracker/traces.py", line 34, in parse_trace
    packet['dissection'] = parse_packet(packet['data'], context[packet['direction']])
  File "/usr/local/lib/python3.8/site-packages/quic_tracker/dissector/__init__.py", line 47, in parse_packet
    raise last_e
  File "/usr/local/lib/python3.8/site-packages/quic_tracker/dissector/__init__.py", line 43, in parse_packet
    return p, parse_packet_with(buffer[:], protocol=yaml.load(f), context=context)
  File "/usr/local/lib/python3.8/site-packages/quic_tracker/dissector/__init__.py", line 65, in parse_packet_with
    raise last_e
  File "/usr/local/lib/python3.8/site-packages/quic_tracker/dissector/__init__.py", line 56, in parse_packet_with
    ret, inc, _ = parse_structure_type(buffer[:], top_struct, protocol, 0, context)
  File "/usr/local/lib/python3.8/site-packages/quic_tracker/dissector/__init__.py", line 101, in parse_structure_type
    raise ParseError('No structure could be parsed for type {}, first byte was {}'.format(type_name, buffer[0]))
quic_tracker.dissector.ParseError: No structure could be parsed for type Version Negotiation Packet, first byte was 246
```

This is the source trace:
```
[{"commit":"","scenario":"Adapter","scenario_version":1,"host":"implementation:4433","ip":"172.29.0.2","results":{},"started_at":1596032468,"duration":0,"error_code":0,"stream":[{"direction":"to_server","timestamp":1596032472788,"data":"wP8AAB0IDTjjQRNLYEUIyVOG2U7UxSgARMoABgBBAwEAAP8DA0AT7RtdLnCIx/VGMjjkjDw9MMwHy3VMSEa9nI0/naBKAAAGEwITARMDAQAA0AAzAEcARQAXAEEEIvsKxBB6EWXgHW/ycz9SVS3V2AnkPbAitJiE9AqXb1GCZ6q3yYH5fn0sK3wYTFt9TcakscQFfjxsZgd2S4qBuQAAABYAFAAAEXF1aWMudGlmZXJyZWkuY29tABAACAAGBWhxLTI5ACsACQgDBH8cfxt/GgANAAoACAgEBAMEAQIBAAoABgAEABcAHf+lAC8FBIAAQAAHBIAAQAAEBIAAgAAIAQEJAQMBBIAJJ8AOAQQDAkXADwjJU4bZTtTFKAAtAAMCAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","is_of_interest":false},{"direction":"to_client","timestamp":1596032472791,"data":"9v8AAB0IyVOG2U7UxSgIj4rN1deU1yHU1vKacwEAAJ06MtRvL3HYWyoxwk0bgFP+gVIr7rENqfCWQ4qKjXiV+wTkbSxM8sgPY9db+HRj4O5RcWachNtSXNYZaWMlh094RDXwAAAAAN9BybZ/YYIKImODrcRP6hs=","is_of_interest":false}],"pcap":null,"qlog":{"qlog_version":"draft-01","title":"QUIC Adapter Trace","description":"QUIC-Tracker","summary":null,"traces":[{"vantage_point":{"name":"QUIC-Tracker","type":"client"},"title":"","description":"Connection to quic.tiferrei.com (172.29.0.2:4433), using version ff00001d and alpn hq-29","configuration":{"time_offset":"0","time_units":"us"},"common_fields":{"ODCID":"0d38e341134b6045","group_id":"0d38e341134b6045","reference_time":1596032468231306},"event_fields":["relative_time","category","event","data"],"events":[[4557145,"transport","packet_sent",{"packet_type":"initial","header":{"packet_number":"0","packet_size":1252,"payload_length":1226,"scil":"8","dcil":"8","scid":"c95386d94ed4c528","dcid":"0d38e341134b6045"},"frames":[{"frame_type":"crypto","offset":"0","length":"259"}]}],[4558556,"transport","packet_received",{"packet_type":"retry","header":{"packet_number":"0","packet_size":119,"scil":"8","dcil":"8","scid":"8f8acdd5d794d721","dcid":"c95386d94ed4c528"}}]]}]},"client_random":"Ya53AjQuKFvHV/4/gRWCqwbVdge3p5VZYiqRpI8yiaE=","secrets":{}}]
```

Any idea what might be happening here? I've been using QUIC-Tracker to debug some traces for a while with no problems. This is the first time I'm trying to visualise a retry, don't know if that's related or more of a red herring. 

Thank you!
Tiago

**Comment by mpiraux** [comment]
It's definitely the Retry packet that was causing this. There is a version whitelist that I have to update every time unfortunately.

**Comment by nqv** [comment]
Hi, I see similar error `quic_tracker.dissector.ParseError: No structure could be parsed for type Version Negotiation Packet, first byte was 0` with this traces:

<details>
<summary>traces...</summary>
<p>

```json
[
  {
    "commit": "",
    "scenario": "transport_parameters",
    "scenario_version": 4,
    "host": "127.0.0.1:4433",
    "ip": "127.0.0.1",
    "results": {
      "decoded_parameters": {
        "ack_delay_exponent": 3,
        "active_connection_id_limit": 2,
        "idle_timeout": 5000,
        "initial_max_data": 1000000,
        "initial_max_stream_data_bidi_local": 100000,
        "initial_max_stream_data_bidi_remote": 100000,
        "initial_max_stream_data_uni": 100000,
        "initial_max_streams_bidi": 8,
        "initial_max_streams_uni": 8,
        "initial_source_connection_id": "ZlLU/VtAjRNknSLeQcVsieTzpgA=",
        "max_ack_delay": 25,
        "max_packet_size": 1232,
        "original_destination_connection_id": "RH0nqXXUq6Y="
      },
      "transport_parameters": { "TransportParameterList": null }
    },
    "started_at": 1597805588,
    "duration": 10009,
    "error_code": 0,
    "stream": [
      {
        "direction": "to_server",
        "timestamp": 1597805588124,
        "data": "wP8AAB0IRH0nqXXUq6YI1rUjvJGM3FkARMoABgBBWgEAAVYDA3fHc6uv3YY+oIzuGpyepdGLf3KEQxuUxqNs4tXj4dvyAAAGEwITARMDAQABJwAzAEcARQAXAEEERfhz2rz+PC0KYhV6HdymEkGB48A3nPXjqvDNpCxtAmWTzfIVw5eMctdssh3Cj6anwC7SbkW5AANvQBZypr15JAAQAAgABgVocS0yOQArAAMCAwQADQAKAAgIBAQDBAECAQAKAAYABAAXAB3/pQCmBQSAAEAABwSAAEAABASAAIAACAEBCQEDAQJnEA4BBAMEgAD/5A8I1rUjvJGM3FmAAP8ABIAA/wCAAP8BBIAA/wGAAP8CBIAA/wKAAP8DBIAA/wOAAP8EBIAA/wSAAP8FBIAA/wWAAP8GBIAA/waAAP8HBIAA/weAAP8IBIAA/wgbAgAbOgIAOkBZAgBZQHgCAHhAlwIAl0C2AgC2QNUCANVA9AIA9AAtAAMCAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "is_of_interest": false
      },
      {
        "direction": "to_client",
        "timestamp": 1597805588125,
        "data": "wP8AAB0I1rUjvJGM3FkUZlLU/VtAjRNknSLeQcVsieTzpgAAQJYAAgBBkwAABgBAewIAAHcDAzMzzEdXXa2yTTtiX8rAeNIUXAx5ifqEJU8Wz1VYWWwMABMCAABPACsAAgMEADMARQAXAEEE9YV+rHv94R6zeP/6Zf5MfKxwVndNaJhS6hpznDlLuqvqMiA0a/jVmqM5HqQtuHPfovWMI11ZNupWU7YgMyP6kQ==",
        "is_of_interest": false
      },
      {
        "direction": "to_client",
        "timestamp": 1597805588126,
        "data": "4P8AAB0I1rUjvJGM3FkUZlLU/VtAjRNknSLeQcVsieTzpgBClAAGAEJ/CAAAYQBfABAACAAGBWhxLTI5/6UATwAIRH0nqXXUq6YBAlOIAwJE0AQEgA9CQAUEgAGGoAYEgAGGoAcEgAGGoAgBCAkBCAoBAwsBGQ4BAg8UZlLU/VtAjRNknSLeQcVsieTzpgALAAGSAAABjgABiTCCAYUwggEroAMCAQICECEYus3jy+piozoqZ/nTbmkwCgYIKoZIzj0EAwIwEjEQMA4GA1UEChMHQWNtZSBDbzAeFw0xNzEwMjAxOTQzMDZaFw0xODEwMjAxOTQzMDZaMBIxEDAOBgNVBAoTB0FjbWUgQ28wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9He1TYW1r2S1j7o/0bRxY77SQRMDpIWzfwZ5xPK52UfPrG8J3PyoQpNxYZ6R2Z0M+weWhE22yIJrr3sHY70gUo2MwYTAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHREEIjAggg5sb2NhbGhvc3Q6NTQ1M4IOMTI3LjAuMC4xOjU0NTMwCgYIKoZIzj0EAwIDSAAwRQIhANs6SRD0Ms+v5Vn/Oml+j3qbJ7Wb9hmJQOVKWm309hGSAiAqSeYf4iPot+NYAZi4gBUDskw0/v8EHOjBffmMNWMtLQAADwAATAQDAEgwRgIhAK1D/LzSoJKIa2aQLM3uOvJ+T6+Ey1oOXPcPGsIqab9TAiEA0mzyJDiOLVK9Ijn6ZrxYejGXpeAr10rF/NoGw3Od7YEUAAAwsDhvQdkbliwzrLtaF485lRdt1ZvgxPPhHTO/eptV6zWeZRP+ELunjd30kLeXEYeB",
        "is_of_interest": false
      },
      {
        "direction": "to_server",
        "timestamp": 1597805588187,
        "data": "wP8AAB0UZlLU/VtAjRNknSLeQcVsieTzpgAI1rUjvJGM3FkARL4BAgBBewAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "is_of_interest": false
      },
      {
        "direction": "to_server",
        "timestamp": 1597805588187,
        "data": "4P8AAB0UZlLU/VtAjRNknSLeQcVsieTzpgAI1rUjvJGM3FlATgACAF5GAAAGADQUAAAwgX69e9+2iQsjoyypNPoOIenhocYnDFK5N46r6lKYLnJmcZLXGsFL+QRMK3d7WqQM",
        "is_of_interest": false
      },
      {
        "direction": "to_client",
        "timestamp": 1597805588190,
        "data": "4P8AAB0I1rUjvJGM3FkUZlLU/VtAjRNknSLeQcVsieTzpgAXAQIAS1cAAA==",
        "is_of_interest": false
      },
      {
        "direction": "to_client",
        "timestamp": 1597805588190,
        "data": "ANa1I7yRjNxZAAYAQJIEAACOAAk6gAAAAAAAAIG+KR3zulMnIYINy1cfoqgGjXZUr3X+/td6lJTNQP2y3P6LQhTzVpRAEZtgNT25CRSGkBi94Qk4fH6k15462zT2iMMVeeYgB4tZ7pIJVdr2HxdMhXXMqGAjnbN9wtDS2ZtYz9shm/RBc7wU4I9ecV9SKJqIIvpHtl2yZMoehQTrnC8AAB4=",
        "is_of_interest": false
      },
      {
        "direction": "to_server",
        "timestamp": 1597805588198,
        "data": "QGZS1P1bQI0TZJ0i3kHFbInk86YAAAIAQ98AAA==",
        "is_of_interest": false
      },
      {
        "direction": "to_server",
        "timestamp": 1597805598062,
        "data": "QGZS1P1bQI0TZJ0i3kHFbInk86YAAQIAgBLlRAAAHQAA",
        "is_of_interest": false
      }
    ],
    "pcap": "1MOyoQIABAAAAAAAAAAAAAAABAABAAAA",
    "qlog": {
      "description": "QUIC-Tracker",
      "qlog_version": "draft-01",
      "summary": null,
      "title": "QUIC-Tracker scenario transport_parameters",
      "traces": [
        {
          "common_fields": {
            "ODCID": "447d27a975d4aba6",
            "group_id": "447d27a975d4aba6",
            "reference_time": 1597805587087002
          },
          "configuration": { "time_offset": "0", "time_units": "us" },
          "description": "Connection to 127.0.0.1 (127.0.0.1:4433), using version ff00001d and alpn hq-29",
          "event_fields": ["relative_time", "category", "event", "data"],
          "events": [
            [
              1037382,
              "transport",
              "packet_sent",
              {
                "frames": [
                  { "frame_type": "crypto", "length": "346", "offset": "0" }
                ],
                "header": {
                  "dcid": "447d27a975d4aba6",
                  "dcil": "8",
                  "packet_number": "0",
                  "packet_size": 1252,
                  "payload_length": 1226,
                  "scid": "d6b523bc918cdc59",
                  "scil": "8"
                },
                "packet_type": "initial"
              }
            ],
            [
              1038092,
              "transport",
              "packet_received",
              {
                "frames": [
                  {
                    "ack_delay": "403",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  },
                  { "frame_type": "crypto", "length": "123", "offset": "0" }
                ],
                "header": {
                  "dcid": "d6b523bc918cdc59",
                  "dcil": "8",
                  "packet_number": "0",
                  "packet_size": 188,
                  "payload_length": 150,
                  "scid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "scil": "20"
                },
                "packet_type": "initial"
              }
            ],
            [
              1038450,
              "transport",
              "packet_buffered",
              { "packet_type": "handshake", "trigger": "keys_unavailable" }
            ],
            [1038509, "recovery", "metrics_updated", { "max_ack_delay": 3 }],
            [
              1039473,
              "transport",
              "packet_received",
              {
                "frames": [
                  { "frame_type": "crypto", "length": "639", "offset": "0" }
                ],
                "header": {
                  "dcid": "d6b523bc918cdc59",
                  "dcil": "8",
                  "packet_number": "0",
                  "packet_size": 697,
                  "payload_length": 660,
                  "scid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "scil": "20"
                },
                "packet_type": "handshake",
                "trigger": "keys_unavailable"
              }
            ],
            [
              1099952,
              "transport",
              "packet_sent",
              {
                "frames": [
                  {
                    "ack_delay": "379",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  }
                ],
                "header": {
                  "dcid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "dcil": "20",
                  "packet_number": "1",
                  "packet_size": 1252,
                  "payload_length": 1214,
                  "scid": "d6b523bc918cdc59",
                  "scil": "8"
                },
                "packet_type": "initial"
              }
            ],
            [
              1100328,
              "transport",
              "packet_sent",
              {
                "frames": [
                  {
                    "ack_delay": "7750",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  },
                  { "frame_type": "crypto", "length": "52", "offset": "0" }
                ],
                "header": {
                  "dcid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "dcil": "20",
                  "packet_number": "0",
                  "packet_size": 115,
                  "payload_length": 78,
                  "scid": "d6b523bc918cdc59",
                  "scil": "8"
                },
                "packet_type": "handshake"
              }
            ],
            [
              1103263,
              "transport",
              "packet_received",
              {
                "frames": [
                  {
                    "ack_delay": "2903",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  }
                ],
                "header": {
                  "dcid": "d6b523bc918cdc59",
                  "dcil": "8",
                  "packet_number": "1",
                  "packet_size": 59,
                  "payload_length": 23,
                  "scid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "scil": "20"
                },
                "packet_type": "handshake"
              }
            ],
            [
              1103263,
              "transport",
              "packet_received",
              {
                "frames": [
                  { "frame_type": "crypto", "length": "146", "offset": "0" },
                  { "frame_type": "handshake_done" }
                ],
                "header": {
                  "dcid": "d6b523bc918cdc59",
                  "dcil": "8",
                  "packet_number": "0",
                  "packet_size": 236
                },
                "packet_type": "1RTT"
              }
            ],
            [
              1103576,
              "recovery",
              "metrics_updated",
              { "latest_rtt": 2, "max_ack_delay": 23 }
            ],
            [
              1111537,
              "transport",
              "packet_sent",
              {
                "frames": [
                  {
                    "ack_delay": "991",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  }
                ],
                "header": {
                  "dcid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "dcil": "20",
                  "packet_number": "0",
                  "packet_size": 44
                },
                "packet_type": "1RTT"
              }
            ],
            [
              11010275,
              "transport",
              "packet_sent",
              {
                "frames": [
                  {
                    "ack_delay": "1238340",
                    "acked_ranges": [[0, 0]],
                    "frame_type": "ack"
                  },
                  {
                    "error_code": "0",
                    "error_space": "application",
                    "frame_type": "connection_close",
                    "reason": ""
                  }
                ],
                "header": {
                  "dcid": "6652d4fd5b408d13649d22de41c56c89e4f3a600",
                  "dcil": "20",
                  "packet_number": "1",
                  "packet_size": 49
                },
                "packet_type": "1RTT"
              }
            ]
          ],
          "title": "",
          "vantage_point": { "name": "QUIC-Tracker", "type": "client" }
        }
      ]
    },
    "client_random": "d8dzq6/dhj6gjO4anJ6l0Yt/coRDG5TGo2zi1ePh2/I=",
    "secrets": {
      "2": {
        "epoch": 2,
        "read": "BVt6QqLJkTzy0x5Bsbd2wJa2s1Ev2iRynlRLKkJqI6rWB7tJ0iICGeZ0Woe0t7FL",
        "write": "Z1QfCunzD+8xDYXy86zWzvXm8J9ScggpKPMZcib9/bKDaoE6Rhks77CmwoSwqz2Q"
      },
      "3": {
        "epoch": 3,
        "read": "yM3yZS3b2ESV/bMWsHyx5hLYBT6ghTxCQMBuNBo3gUHDsH9+bk8g7bOorr9g7gwo",
        "write": "aV7hnXkQucwhZfbjEFJVghaEKlJPMokYofP+tMwkbCXypC2l9t59cU0QLjSuJDay"
      }
    }
  }
]
```
</p>
</details>

It failed at parsing `ANa1I7yRjNxZAAYAQJIEAACOAAk6gAAAAAAAAIG...`. I'm not sure why it thought it's Version Negotiation.

**Comment by mpiraux** [comment]
Hi! So the packet is:

```
0000	00 d6 b5 23 bc 91 8c dc 59 00 06 00 40 92 04 00
0010	00 8e 00 09 3a 80 00 00 00 00 00 00 81 be 29 1d
0020	f3 ba 53 27 21 82 0d cb 57 1f a2 a8 06 8d 76 54
0030	af 75 fe fe d7 7a 94 94 cd 40 fd b2 dc fe 8b 42
0040	14 f3 56 94 40 11 9b 60 35 3d b9 09 14 86 90 18
0050	bd e1 09 38 7c 7e a4 d7 9e 3a db 34 f6 88 c3 15
0060	79 e6 20 07 8b 59 ee 92 09 55 da f6 1f 17 4c 85
0070	75 cc a8 60 23 9d b3 7d c2 d0 d2 d9 9b 58 cf db
0080	21 9b f4 41 73 bc 14 e0 8f 5e 71 5f 52 28 9a 88
0090	22 fa 47 b6 5d b2 64 ca 1e 85 04 eb 9c 2f 00 00
00a0	1e 
```

The QUIC bit is not set in the first byte, so the dissector fails identifiying it as a QUIC packet. Do you grease it ? QUIC-Tracker doesn't support that ATM. I guess it's a short header packet. The dissector does trial and error when dissecting, the last message reported in the error is usually not so valuable.

**Comment by nqv** [comment]
You're right, it's my bad. Thank you for taking a look. I really appreciate it.
